# Generated by Django 6.0.4 on 2026-05-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(db_index=True, default=-1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
